### ISSUE TITLE
Error: The Cl map needed for the ligand was not found in the .fld file!

### ISSUE THREAD

**Issue by ricomnl** [ccsb-scripps/AutoDock-GPU#142]
I keep getting this error:
Error: The Cl map needed for the ligand was not found in the .fld file!

Where can I define the ligand_types from the Autodock .dpf file here?

**Comment by atillack** [comment]
@rmeinl The ligand types are taken directly from the ligand pdbqt file in AD-GPU. And while you could also use the `--import_dpf <AD4 .dpf file` command line option to directly import and run them this will likely not fix your issue ...

We have seen this behavior sometimes on Linux due to more stringent case-sensitivity on the file system side compared to other operating systems (for whom *.CL.map and *.Cl.map are the same ...). Depending on which OS (macOS and Windows are case-insensitive for example) was used to prepare the grid maps what happens is that autogrid4 will, for example, create receptor.CL.map first and then when it creates receptor.Cl.map this will unfortunately lead to the existing receptor.CL.map file being overwritten.

The solution fortunately is to simply create a copy or a symlink from one or the other (i.e. if receptor.CL.map exist for example you could do an `ln -sf receptor.CL.map receptor.Cl.map`).

Another solution of course is to rerun grid map creation using autogrid4 on the target OS - if (as is usually the case) both CL and Cl ligand types are specified in the gpf file.

**Comment by ricomnl** [comment]
Got it thanks! Preparing the files on the same OS worked
