### ISSUE TITLE
unable to execute batch file operation (--filelist)

### ISSUE THREAD

**Issue by parazue** [ccsb-scripps/AutoDock-GPU#145]
ram@ram:~/Documents/Debanjan-PV-work$ cd NP-AtDB-Vs-4jsv/
ram@ram:~/Documents/Debanjan-PV-work/NP-AtDB-Vs-4jsv$ gpu_dock --filelist lig_list.txt --xmloutput 0 --contact_analysis 1 --nrun 10
AutoDock-GPU version: v1.4-release

ram@ram:~/Documents/Debanjan-PV-work/NP-AtDB-Vs-4jsv$ gpu_dock --filelist lig_list.txt  --nrun 10
AutoDock-GPU version: v1.4-release

ram@ram:~/Documents/Debanjan-PV-work/NP-AtDB-Vs-4jsv$ gpu_dock --filelist lig_list.txt
AutoDock-GPU version: v1.4-release

ram@ram:~/Documents/Debanjan-PV-work/NP-AtDB-Vs-4jsv$ 

This programme is working for single ligand (--ffile) but unable to execute for batch file (--filelist)

**Comment by atillack** [comment]
@parazue This is odd - is there no error output at all? (maybe a mention of a "segfault" or anything). What OS are you running on (it looks like it may be macOS) and which version? On macOS, I currently run on Big Sur 11.4 and before that I was running on Catalina.

**Comment by parazue** [comment]
Am using ubuntu 18.04, in the previous version I have done VS it was running fine. The ligand list file format is given below protein.map.fld
ligand1.pdbqt
ligand2pdbqt
ligand3pdbqt
and so on.
In addition, the folder contains all map files.

**Comment by atillack** [comment]
@parazue Thank you for the additional information - there is a `.` after ligand2 and ligand3, right? (just a Cpt. Obvious check ...)

It's really weird you don't get any output other than the version, so it might take a bit of time here to find out what's wrong ... 

To get another datapoint, could you test the current PR #139 ? It contains (besides a ton of new features) a lot of changes in that area of code that may be helpful.

**Comment by debanjansen48** [comment]
I am using Linuxmint 19.3. Me, too, facing same issue. I thought that was a compilation issue. But previous version working nicely.

(base) debanjan@debanjan:/media/debanjan/DS-1TB/protein/Denovo-ligs$ autodock_gpu_256wi 
AutoDock-GPU version: 

CUDA Setup time 0.092084s
(Thread 0 is setting up Job 0)
Error: grid fld file was not defined. Use -ffile argument!


Error in get_filenames_and_ADcoeffs, stopped job.

Error in setup of Job #0:

Run time of entire job set (1 files): 0.103 sec
Savings from multithreading: -0.103 sec
Idle time of execution thread: 0.103 sec
The job was not successful.(base) debanjan@debanjan:/media/debanjan/DS-1TB/protein/Denovo-ligs$ 


debanjan@debanjan:/media/debanjan/DS-1TB/NSP:autodock_gpu_256wi -filelist lig_list.txt -nrun 10
Running 21697 jobs in pipeline mode
AutoDock-GPU version: 

CUDA Setup time 0.080474s
(Thread 0 is setting up Job 0)

Error: The Br map needed for the ligand was not found in the .fld file!

Error in copy_from_all_maps, stopped job.

Error in setup of Job #0:
(   Field file: ./protein-rec_h.maps.fld )
(   Ligand file: NPC100002.pdbqt )
(Thread 0 is setting up Job 1)

Running Job #1:
   Fields from: ./protein-rec_h.maps.fld
   Ligands from: NPC100039.pdbqt
RNG seed is 1623256997
Local-search chosen method is: Solis-Wets (sw)

Rest of Setup time 0.006156s

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************
Docking time 1.010951s


Shutdown time 0.000157s

Job #1 took 1.017 sec after waiting 1.281 sec for setup

(Thread 0 is processing Job 1)
(Thread 0 is setting up Job 2)

Running Job #2:
   Fields from: ./protein-rec_h.maps.fld
   Ligands from: NPC100049.pdbqt
RNG seed is 1623256998
Local-search chosen method is: Solis-Wets (sw)

Rest of Setup time 0.005778s

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
****************************************

that was running



**But**

(base) debanjan@debanjan:/media/debanjan/DS-1TB/NSP-10/NP/NP-vs$ new_autodock_gpu_256wi 
AutoDock-GPU version: 

Running 1 docking calculation

Cuda device:                              GeForce RTX 2070 SUPER
Available memory on device:               6952 MB (total: 7981 MB)

CUDA Setup time 0.078562s
Error: grid fld file was not defined. Use -ffile argument!


Error in get_filenames_and_ADcoeffs, stopped job.

Error in setup of Job #1:
Run time of entire job set (1 file): 0.081 sec
Processing time: 0.000 sec
The job was not successful.
(base) debanjan@debanjan:/media/debanjan/DS-1TB/NSP-10/NP/NP-vs$ new_autodock_gpu_256wi -filelist lig_list.txt -nrun 10
AutoDock-GPU version: 

not running

**Comment by debanjansen48** [comment]
The presence or absence  of "." before the ligand name shows no improvement. No output with new version.

**Comment by atillack** [comment]
Is the new version 1.4.2 or PR #139?

**Comment by atillack** [comment]
Also, which version is the "old" version that seemed to run the file list correctly on your Linux Mint machine?

**Comment by parazue** [comment]
Am using ubuntu 18.04, in the previous version I have done VS it was running fine. The ligand list file format is given below protein.map.fld
ligand1.pdbqt
ligand2.pdbqt
ligand3.pdbqt
and so on.
In addition, the folder contains all map files.

**Comment by debanjansen48** [comment]
The old version did not return any Version number
However, the readme.md file of the old version I am sending.

 AutoDock-GPU: AutoDock for GPUs and other accelerators
======================================================

<img src="logo.png" width="200">

# About

* OpenCL and Cuda accelerated version of AutoDock4.2.6. It leverages its embarrasingly parallelizable LGA by processing ligand-receptor poses in parallel over multiple compute units.
* The OpenCL version was developed in collaboration with TU-Darmstadt and is able to target CPU, GPU, and FPGA architectures.
* The Cuda version was developed in collaboration with Nvidia to run AutoDock-GPU on the Oak Ridge National Laboratory's (ORNL) Summit, and it included a batched ligand pipeline developed by Aaron Scheinberg from Jubilee Development.

# Features

* Besides the legacy Solis-Wets local search method, AutoDock-GPU adds newly implemented local-search methods based on gradients of the scoring function. One of these methods, ADADELTA, has proven to increase significantly the docking quality in terms of RMSDs and scores.
* It targets platforms based on GPU as well as multicore CPU accelerators.
* Observed speedups of up to 4x (quad-core CPU) and 56x (GPU) over the original serial AutoDock 4.2 (Solis-Wets) on CPU. The Cuda version is currently even faster than the OpenCL version.
* A batched ligand pipeline to run virtual screenings on the same receptor (both OpenCL and Cuda)

# Setup

| Operating system                         | CPU                          | GPU                                            |
|:----------------------------------------:|:----------------------------:|:----------------------------------------------:|
|CentOS 6.7 & 6.8 / Ubuntu 14.04 & 16.04   | Intel SDK for OpenCL 2017    | AMD APP SDK v3.0 / CUDA v8.0, v9.0, and v10.0  |
|macOS Catalina 10.15.1                    | Apple / Intel                | Apple / Intel Iris, Radeon Vega 64, Radeon VII |


Other environments or configurations likely work as well, but are untested.

# Compilation

```zsh
make DEVICE=<TYPE> NUMWI=<NWI>
```

| Parameters | Description                  | Values                                             |
|:----------:|:----------------------------:|:--------------------------------------------------:|
| `<TYPE>`   | Accelerator chosen           | `CPU`, `GPU`, `CUDA`, `OCLGPU`                     |
| `<NWI>`    | work-group/thread block size | `1`, `2`, `4`, `8`, `16`, `32`, `64`, `128`, `256` |

When `DEVICE=GPU` is chosen, the Makefile will automatically tests if it can compile Cuda succesfully. To override, use `DEVICE=CUDA` or `DEVICE=OCLGPU`. The cpu target is only supported using OpenCL.
Hints: The best work-group size depends on the GPU and workload. Try `NUMWI=128` or `NUMWI=64` for modern cards with the example workloads. On macOS, use `NUMWI=1` for CPUs.

After successful compilation, the host binary **autodock_&lt;type&gt;_&lt;N&gt;wi** is placed under [bin](./bin).

| Binary-name portion | Description                  | Values                                            |
|:-------------------:|:----------------------------:|:-------------------------------------------------:|
| **&lt;type&gt;**    | Accelerator chosen           | `cpu`, `gpu`                                      |
| **&lt;N&gt;**       | work-group/thread block size | `1`, `2`, `4`, `8`,`16`, `32`, `64`, `128`, `256` |


# Usage

## Basic command
```zsh
./bin/autodock_<type>_<N>wi \
-ffile <protein>.maps.fld \
-lfile <ligand>.pdbqt \
-nrun <nruns>
```

| Mandatory options | Description   | Value                     |
|:-----------------:|:-------------:|:-------------------------:|
| -ffile            |Protein file   |&lt;protein&gt;.maps.fld   |
| -lfile            |Ligand file    |&lt;ligand&gt;.pdbqt       |

## Example
```zsh
./bin/autodock_gpu_64wi \
-ffile ./input/1stp/derived/1stp_protein.maps.fld \
-lfile ./input/1stp/derived/1stp_ligand.pdbqt \
-nrun 10
```
By default the output log file is written in the current working folder. Examples of output logs can be found under [examples/output](examples/output/).

## Supported arguments

| Argument    | Description                                           | Default value    |
|:------------|:------------------------------------------------------|-----------------:|
| -nrun       | # LGA runs                                            | 1                |
| -nev        | # Score evaluations (max.) per LGA run                | 2500000          |
| -ngen       | # Generations (max.) per LGA run                      | 27000            |
| -lsmet      | Local-search method                                   | sw (Solis-Wets)  |
| -lsit       | # Local-search iterations (max.)                      | 300              |
| -psize      | Population size                                       | 150              |
| -mrat       | Mutation rate                                         | 2 (%)            |
| -crat       | Crossover rate                                        | 80 (%)           |
| -lsrat      | Local-search rate                                     | 80 (%)           |
| -trat       | Tournament (selection) rate                           | 60 (%)           |
| -resnam     | Name for docking output log                           | _"docking"_      |
| -hsym       | Handle symmetry in RMSD calc.                         | 1                |
| -devnum     | OpenCL/Cuda device number (counting starts at 1)      | 1                |
| -cgmaps     | Use individual maps for CG-G0 instead of the same one | 0 (use same map) |
| -heuristics | Ligand-based automatic search method and # evals      | 0                |
| -heurmax    | Asymptotic heuristics # evals limit (smooth limit)    | 50000000         |
| -autostop   | Automatic stopping criterion based on convergence     | 0                |
| -asfreq     | Autostop testing frequency (in # of generations)      | 5                |
| -initswgens | Initial # generations of Solis-Wets instead of -lsmet | 0                |
| -filelist   | Batch file                                            | no default       |
| -xmloutput  | Specify if xml output format is wanted                | 1 (yes)          |

When the heuristics is used and `-nev <max evals>` is provided as a command line argument it provides the (hard) upper # of evals limit to the value the heuristics suggests. Conversely, `-heurmax` is the rolling-off type asymptotic limit to the heuristic's # of evals formula and should only be changed with caution.
The batch file is a text file containing the parameters to -ffile, -lfile, and -resnam each on an individual line. It is possible to only use one line to specify the Protein grid map file which means it will be used for all ligands. Here is an example:
```
./receptor1.maps.fld
./ligand1.pdbqt
Ligand 1
./receptor2.maps.fld
./ligand2.pdbqt
Ligand 2
./receptor3.maps.fld
./ligand3.pdbqt
Ligand 3
```

For a complete list of available arguments and their default values, check [getparameters.cpp](host/src/getparameters.cpp).

# Documentation

Visit the project [Wiki](https://github.com/ccsb-scripps/AutoDock-GPU/wiki).

**Comment by atillack** [comment]
Thank you, that narrows it down a little. And what you said was the "new version" is the newest release or did you try PR #139?

**Comment by debanjansen48** [comment]
Yes new version means 1.4.2 the recent one. Old version means the version I
download in the month of September 2020.

**Comment by atillack** [comment]
Thank you. What output is `nvidia-smi` giving you and which Cuda version are you compiling against? I suspect that this could be a case of multiple libraries being present and used at compile vs run time.

Make sure to adjust `GPU_INCLUDE_PATH` and `GPU_LIBRARY_PATH` to that path and also make sure that `nvcc` is the correct version from that path.

Example: if you updated to Cuda 10.2 it would go into `/usr/local/cuda-10.2` by default and you'd want to make sure `which nvcc` then would show `/usr/local/cuda-10.2/bin/nvcc` (you may need to add this to your `PATH`) and the defines above should then be set to `GPU_INCLUDE_PATH=/usr/local/cuda-10.2/include` and `GPU_LIBRARY_PATH=/usr/local/cuda-10.2/lib64` ...

**Comment by debanjansen48** [comment]
Actually, during my 1st time compilation, I encountered by path issues.
According I received superior support from your end. Still same settings I
am using. I did not changed a single line from ~/•bashrc.. Using that I
communicated one work with is under 2nd phase of review sir. Thank you.

**Comment by debanjansen48** [comment]
Sir just now I compiled, old version [ref: [ccsb-scripps/AutoDock-GPU] Unable to compile (#80)]
and working nicely, but problem with recent one.

**Comment by atillack** [comment]
@debanjansen48 Thank you

@parazue @debanjansen48 I found the culprit ...  it's a bug in the code (that i introduced) - thank you for pointing it out :-) 

There will be a version 1.4.3 coming up soon ...

**Comment by debanjansen48** [comment]
Thank you sir, kindly do something that we can use Autodock Zn force field. In addition, it will be helpful if there is a tool to convert large small molecule library in pdbqt format with GPU acceleration (maybe currently you are not focussing on it). But we really need such tools. Thank you sir.

**Comment by atillack** [comment]
@debanjansen48 @parazue The bug fixed version is up as a new release.

**Comment by debanjansen48** [comment]
**THANK YOU............... ITS NOW WORKING....I am so Happy**

New2-autodock_gpu_64wi -filelist lig_list.txt -nrun 10
AutoDock-GPU version: v1.4-release

Running 21697 docking calculations

Cuda device:                              GeForce RTX 2070 SUPER
Available memory on device:               7341 MB (total: 7981 MB)

CUDA Setup time 0.097162s
Error: can't open ligand data file .NPC100002.pdbqt!


Error in init_liganddata, stopped job.

Error in setup of Job #1:
(   Grid map file: ./Prot-rec_h.maps.fld )
(   Ligand file: .NPC100002.pdbqt )
Error: can't open ligand data file .NPC100039.pdbqt!


Error in init_liganddata, stopped job.

Error in setup of Job #2:
(   Grid map file: ./Prot-rec_h.maps.fld )
(   Ligand file: .NPC100039.pdbqt )
Error: can't open ligand data file .NPC100049.pdbqt!


Error in init_liganddata, stopped job.

Error in setup of Job #3:
(   Grid map file: ./Prot-rec_h.maps.fld )
(   Ligand file: .NPC100049.pdbqt )

Running Job #4:
    Grid map file: ./Prot-rec_h.maps.fld
    Ligand file: NPC100067.pdbqt
    Using heuristics: (capped) number of evaluations set to 4195460
    Local-search chosen method is: ADADELTA (ad)

Rest of Setup time 0.001656s

Executing docking runs, stopping automatically after either reaching 0.15 kcal/mol standard deviation of
the best molecules of the last 4 * 5 generations, 42000 generations, or 4195460 evaluations:

Generations |  Evaluations |     Threshold    |  Average energy of best 10%  | Samples |    Best energy
------------+--------------+------------------+------------------------------+---------+-------------------
          0 |          150 |    6.12 kcal/mol |    1.40 +/-    1.47 kcal/mol |       7 |   -1.74 kcal/mol
          5 |        62111 |    4.54 kcal/mol |   -5.88 +/-    2.10 kcal/mol |     455 |  -12.22 kcal/mol
         10 |       141699 |   -5.81 kcal/mol |  -10.80 +/-    0.73 kcal/mol |      29 |  -12.73 kcal/mol
         15 |       235538 |  -10.42 kcal/mol |  -12.75 +/-    0.45 kcal/mol |       8 |  -13.09 kcal/mol
         20 |       341788 |  -11.91 kcal/mol |  -12.61 +/-    0.39 kcal/mol |       4 |  -13.10 kcal/mol
         25 |       455709 |  -11.14 kcal/mol |  -12.29 +/-    0.37 kcal/mol |      10 |  -13.10 kcal/mol
         30 |       575109 |  -11.74 kcal/mol |  -12.93 +/-    0.18 kcal/mol |       5 |  -13.10 kcal/mol
         35 |       695446 |  -12.40 kcal/mol |  -13.21 +/-    0.12 kcal/mol |       4 |  -13.33 kcal/mol
         40 |       818859 |  -12.77 kcal/mol |  -13.29 +/-    0.14 kcal/mol |       3 |  -13.43 kcal/mol
         45 |       944765 |  -12.60 kcal/mol |  -13.19 +/-    0.21 kcal/mol |       4 |  -13.43 kcal/mol
         50 |      1069765 |  -12.41 kcal/mol |  -13.28 +/-    0.16 kcal/mol |       7 |  -13.43 kcal/mol
         55 |      1195524 |  -12.93 kcal/mol |  -13.19 +/-    0.16 kcal/mol |       6 |  -13.43 kcal/mol
         60 |      1319702 |  -12.78 kcal/mol |  -13.26 +/-    0.17 kcal/mol |       4 |  -13.43 kcal/mol
         65 |      1443361 |  -12.63 kcal/mol |  -13.24 +/-    0.18 kcal/mol |       5 |  -13.44 kcal/mol
         70 |      1568920 |  -12.70 kcal/mol |  -13.36 +/-    0.13 kcal/mol |       5 |  -13.44 kcal/mol
         75 |      1695880 |  -12.97 kcal/mol |  -13.42 +/-    0.04 kcal/mol |       5 |  -13.48 kcal/mol
         80 |      1821419 |  -12.97 kcal/mol |  -13.30 +/-    0.18 kcal/mol |       5 |  -13.48 kcal/mol
         85 |      1945998 |  -12.78 kcal/mol |  -13.05 +/-    0.20 kcal/mol |      12 |  -13.48 kcal/mol
         90 |      2070403 |  -12.80 kcal/mol |  -13.09 +/-    0.23 kcal/mol |       9 |  -13.51 kcal/mol
         95 |      2197692 |  -12.71 kcal/mol |  -13.18 +/-    0.20 kcal/mol |       9 |  -13.51 kcal/mol
        100 |      2324461 |  -12.84 kcal/mol |  -13.11 +/-    0.18 kcal/mol |      12 |  -13.51 kcal/mol
        105 |      2450166 |  -12.88 kcal/mol |  -13.14 +/-    0.18 kcal/mol |      11 |  -13.51 kcal/mol
        110 |      2577722 |  -12.89 kcal/mol |  -13.50 +/-    0.02 kcal/mol |       4 |  -13.51 kcal/mol
        115 |      2705616 |  -12.94 kcal/mol |  -13.20 +/-    0.20 kcal/mol |       7 |  -13.51 kcal/mol
        120 |      2833311 |  -12.77 kcal/mol |  -13.09 +/-    0.19 kcal/mol |      15 |  -13.51 kcal/mol
        125 |      2960958 |  -12.89 kcal/mol |  -13.42 +/-    0.09 kcal/mol |       8 |  -13.51 kcal/mol
        130 |      3088646 |  -13.25 kcal/mol |  -13.51 +/-    0.02 kcal/mol |       4 |  -13.54 kcal/mol
        135 |      3218181 |  -12.95 kcal/mol |  -13.42 +/-    0.16 kcal/mol |       4 |  -13.54 kcal/mol
        140 |      3345226 |  -12.81 kcal/mol |  -13.08 +/-    0.21 kcal/mol |      20 |  -13.54 kcal/mol
        145 |      3472993 |  -12.92 kcal/mol |  -13.17 +/-    0.20 kcal/mol |      18 |  -13.54 kcal/mol
        150 |      3599463 |  -13.00 kcal/mol |  -13.25 +/-    0.17 kcal/mol |      20 |  -13.54 kcal/mol
        155 |      3725695 |  -13.12 kcal/mol |  -13.39 +/-    0.14 kcal/mol |      10 |  -13.59 kcal/mol
        160 |      3855053 |  -13.18 kcal/mol |  -13.42 +/-    0.15 kcal/mol |       6 |  -13.59 kcal/mol
        165 |      3983696 |  -13.05 kcal/mol |  -13.44 +/-    0.11 kcal/mol |      12 |  -13.59 kcal/mol
        170 |      4111490 |  -13.31 kcal/mol |  -13.54 +/-    0.05 kcal/mol |       5 |  -13.59 kcal/mol
------------+--------------+------------------+------------------------------+---------+-------------------

                                   Finished evaluation after reaching
                                  -13.44 +/-    0.13 kcal/mol combined.
                                33 samples, best energy   -13.59 kcal/mol.

Docking time 3.071150s

Shutdown time 0.000169s

Job #4 took 3.073 sec after waiting 0.812 sec for setup

**Comment by kmyaca** [comment]
Hello and thank you for the support.

I just came across a new error while trying to run v1.4.3 in batch mode (-B) with the same inputs that used to work so far.

the -B input looks like:

path/to/input.maps.fld
lig1.pdqbt
docked_lig1
...
lig160.pdqbt
docked_lig160

Any idea about the reason and possible fixes?

Thank you.

####

AutoDock-GPU version: 1.4.3

Running 160 docking calculations

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN256WI   -cl-mad-enable
OpenCL device:                           NVIDIA GeForce RTX 2080 Ti
pMem_fgrids: failed to upload maps to GPU memory. -30
./ finished



Upon reinstalling CUDA, batch mode fails returning:

CUDA Setup time 0.125990s
pMem_fgrids: failed to upload maps to GPU memory.
 invalid argument
autodock_gpu_256wi: ./host/src/performdocking.cpp:106: void copy_map_to_gpu(GpuTempData&, std::vector<Map>&, int, int): Assertion `0' failed.
Aborted (core dumped)

**Comment by atillack** [comment]
@kmyaca This error happens when the fld file contains too many maps (>31) currently. This will be one of the things fixed in the next release but for the moment the solution is to reduce the number of maps in the fld file.

**Comment by kmyaca** [comment]
> @kmyaca This error happens when the fld file contains too many maps (>31) currently. This will be one of the things fixed in the next release but for the moment the solution is to reduce the number of maps in the fld file.

Thank you @atillack, it fixed the problem!

**Comment by atillack** [comment]
@kmyaca Version 1.5 is out and contains the code to allow as many maps in the fld file as will fit into memory - the 31 grid map limit now only applies to individual ligands :-)
