### ISSUE TITLE
AutoDock Zn forcefield

### ISSUE THREAD

**Issue by debanjansen48** [ccsb-scripps/AutoDock-GPU#148]
Can I use AutodockZN force field with gpu accelarated AutoDock ?

**Comment by diogomart** [comment]
Yes :)

We have recently made the AD4Zn forcefield available in Vina and wrote this tutorial:
https://autodock-vina.readthedocs.io/en/latest/docking_zinc.html

The associated scripts are available in the Vina repository:
https://github.com/ccsb-scripps/AutoDock-Vina/tree/develop/example/autodock_scripts 

You can follow steps 1, 2, and 3 from that tutorial and then instead of running Vina you run AutoDock-GPU:
```
autodock-gpu --lfile 1s63_ligand.pdbqt --ffile protein_tz.maps.fld --resnam output-filename
```

Let me know if it works for you!

(note: some overlap with #113)
