### ISSUE TITLE
Batch Mode only uses ONE thread after using python's multiprocessing

### ISSUE THREAD

**Issue by NiBoyang** [ccsb-scripps/AutoDock-GPU#201]
**Describe the bug**
Hi, I'm calling the AutoDock-GPU in a python script using `subprocess.check_call`. Before that, I needed to do some pre-processing work to plenty of files so I used `multiprocess.Pool` to accelerate it, but it would cause the batch mode to fail, i.e., only one thread will be used.  This issue also happens using `Ray`

But if I split my workflow into two, i.e., by calling `pre-process.py` and `call-ad.py` separately, this issue will not happen and the batch mode works well.

**To Reproduce**
`if __name__ == "__main__":`
    `with Pool() as pool:`
        `pool.map(multiprocess_libpath, os.listdir(lib_path))`
`subprocess.check_call(f"/root/AutoDock-GPU/bin/autodock_gpu_64wi -B {lig_path}/docking_file.lst -D all --nrun 100 --xmloutput 0", shell=True)`

- Latest Version of AutoDock-GPU
- Ubuntu 20.04
- `make DEVICE=CUDA NUMWI=64 OVERLAP=ON`
- CUDA 11.5
- 4 x RTX3090; 4 x CPU with totally 96 cores

**Comment by atillack** [comment]
@NiBoyang Although the indentation is gone in the posted lines it almost looks like the subprocess call to AD-GPU is part of the parallel pool ... AD-GPU with the parallelized batch processing should not have multiple instances concurrently running as they will fight for resources in that case. I think the intention is to have a parallelized pre-processing step followed after that is done by parallel batch processing, right?

My best guess currently is that once multiprocess is finished it may return to one instance of the python code on a single thread and that it may also set environment variables (like `OMP_NUM_THREADS` for example) accordingly. Since AD-GPU is using OpenMP (and thus would obey `OMP_NUM_THREADS=1`) this may cause it to run with only a single thread.

**Comment by sforli** [comment]
Hi Ni,
your code lost all the indentation, so I'm guessing this is what it looks like in the original, is it correct? (Andreas beat me by a bit :) )

```
if __name__ == "__main__":
    with Pool() as pool:
      pool.map(multiprocess_libpath, os.listdir(lib_path))
    subprocess.check_call(f"/root/AutoDock-GPU/bin/autodock_gpu_64wi -B {lig_path}/docking_file.lst -D all --nrun 100 --xmloutput 0", shell=True)
```

As Andreas suggested, ADGPU might use the OMP_NUM_THREADS variable, which could be modified by the multiprocess module. You can print the env variables after running the multiprocessing pool with this code:
```
import os
env = os.environ.copy()
print(env)
```
and if you see the condition Andreas suggested, you can modify the variable with this:
```
env.update(OMP_NUM_THREADS=96)
subprocess.check_call(f"/root/AutoDock-GPU/bin/autodock_gpu_64wi ...", shell=True, env=env)

```

**Comment by NiBoyang** [comment]
`env = os.environ.copy().update(OMP_NUM_THREADS=96)` did solve the issue! Thanks Andreas and Stefano
