### ISSUE TITLE
Minor potential issue in initialization

### ISSUE THREAD

**Issue by ascheinb** [ccsb-scripps/AutoDock-GPU#74]
The PGI compiler caught this one:

```
./host/src/calcenergy.cpp(138): warning: pointless comparison of unsigned integer with zero

./host/src/calcenergy.cpp(138): warning: pointless comparison of unsigned integer with zero

"./host/src/calcenergy.cpp", line 138: warning: pointless comparison of
          unsigned integer with zero
  if (rotbond_candidate < 0) {
```

Looks like this was intended as a failsafe to exit the loop if something goes wrong. The failsafe doesn't work because `rotbond_candidate` is a char, so if it gets below zero it'll just loop back around. Could just change it to an int. However since this hasn't caused a problem for y'all, I guess the failsafe is redundant anyway.

**Comment by L30nardoSV** [comment]
Many thanks for the feedback @ascheinb !

This seems to be particular to PGI as I do not see this happening with g++ (default compiler for AutoDock-GPU), where plain chars seem to be treated as signed. 

A `char` type was chosen for `rotbond_candidate` (see [here](https://github.com/ccsb-scripps/AutoDock-GPU/blob/master/host/src/calcenergy.cpp#L439)) since it is enough to carry all possible rotatable-bond IDs  (AutoDock supports a max. of 32 rotatable bonds). 

Any particular reason/requirement why you are using PGI?

**Comment by ascheinb** [comment]
Ah, interesting. No, I don't need to use PGI. It's just my personal default on Summit.

**Comment by L30nardoSV** [comment]
Closing this, feel free to re-open it if required.
