### ISSUE TITLE
Covalent docking?

### ISSUE THREAD

**Issue by louetme** [ccsb-scripps/AutoDock-GPU#93]
I tried covalent docking as available in normal Autodock4 with the atom type "Z" but it seems this atom type is not recognized by the GPU version.

I got: "Error: Ligand includes atom with unknown type: A or Z!" I checked in the file processligand.cpp and indeed there is no atom type "Z".

Do you plan to implement this feature?

Thanks

Maxime

**Comment by diogomart** [comment]
Hi,

It's not yet supported in the GPU version, but it's likely it will be in
the future.

Best,

**Comment by WilliamWWolff** [comment]
Hello,

I can see that this is still an open issue on GitHub, but was wondering if you had a vague timeline for implementing covalent docking - though I imagine you must have other priorities!

William

**Comment by diogomart** [comment]
Hi William,

We have been developing a workflow for covalent docking in autodock-gpu, which involves preparing a flexible sidechain with [meeko](https://github.com/forlilab/Meeko). You'll need to `git clone` or download the meeko repository and install with `pip install .`, as opposed to getting it from PyPI, because we haven't created a github/PyPI release with the recent code that handles covalent ligand preparation.

When running the command line tool `mk_prepare_ligand.py`, the relevant arguments are:
```console
Covalent docking (tethered):
  --receptor RECEPTOR   receptor filename. Supported formats: [pdb/mmcif]
  --rec_residue REC_RESIDUE
                        examples: "A:LYS:204", "A:HIS:", ":LYS:"
  --tether_smarts TETHER_SMARTS
                        SMARTS pattern to define ligand atoms for receptor attachment
  --tether_smarts_indices IDX IDX
                        indices (1-based) of the SMARTS atoms that will be attached (default: 1 2)
```
the ligand must be modified to include the sidechain and the alpha carbon, but not the other backbone atoms. As an example, consider an acrylamide reacting with a cysteine. The ligand is `R-NC(=O)C=C`, but what's passed to meeko must be `R-NC(=O)C-CSCC`, and the SMARTS pattern could be `--tether_smarts CCSCC(=O)N --tether_smarts_indices 1 2`, as atoms 1 and 2 in the SMARTS are the alpha- and beta-carbons, respectively.

**Comment by agoliaei** [comment]
Hi @diogomart 
Thanks for your help. 
What is the next step after preparing the ligand? How the actual docking is done in AD-GPU?
